---
- name: Build tar
  hosts: localhost
  vars_files:
    - vars/main.yml
    - vars/db_credentials.yml
  become: true
  become_user: root
  roles:
    - vgcn.config

- name: Copy tar
  hosts: dnbd-server
  vars_files:
    - vars/main.yml
  tasks:
    - name: Copy tarball to /tmp on remote server
      ansible.builtin.copy:
        src: "{{ root_directory.path }}config_bundle.tgz"
        dest: "{{ dnbd_http_dir }}/config.tgz.r{{ build_number }}"
        owner: apache
        group: apache
        mode: '644'
    - name: Change symlink
      ansible.builtin.file:
        state: link
        src: "{{ dnbd_http_dir }}/config.tgz.r{{ build_number }}"
        path: "{{ dnbd_http_dir }}/config.tgz"
    - name: Fix SELINUX permissions
      ansible.builtin.command:
        cmd: /sbin/restorecon -F -R -v /images/netboot/http/
