---
- name: Build tar
  hosts: localhost
  vars_files:
    - vars/main.yml
    - vars/db_credentials.yml
  become: true
  become_user: root
  roles:
    - vgcn.config

- name: Copy tar
  hosts: dnbd-server
  vars_files:
    - vars/main.yml

  tasks:
  - name: Copy tarball to /tmp on remote server
    ansible.builtin.copy:
      src: "{{ root_directory.path }}config_bundle.tgz"
      dest: "/tmp/"
      owner: centos
      group: centos
      mode: '644'