---
- name: Create directories for configuration files
  file:
    path: "{{ [root_directory.path, item.dest] | path_join | dirname }}"
    state: directory
  loop: "{{ config_templates }}"

- name: Clone the https://github.com/usegalaxy-eu/mounts repository
  git:
    repo: "https://github.com/usegalaxy-eu/mounts"
    dest: "/tmp/mounts/"
    clone: yes
    update: yes

- name: Include vars of mountpoints.yml into the 'mounts' variable
  ansible.builtin.include_vars:
    file: /tmp/mounts/mountpoints.yml
    name: mounts

- name: Deploy configuration templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ [root_directory.path, item.dest] | path_join }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ config_templates }}"

- name: Tar the folder structure
  community.general.archive:
    path: "{{ root_directory.path }}"
    dest: "{{ [root_directory.path, 'archive.tgz'] | path_join }}"
    format: gz
    owner: "ubuntu"
    group: "ubuntu"
    mode: "755"