---
- name: Create directories for configuration files
  file:
    path: "{{ [root_directory.path, item.dest] | path_join | dirname }}"
    state: directory
    mode: "755"
  loop: "{{ config_templates }}"

- name: Create /home/centos/.ssh directory
  file:
    path: "{{ home_directory.path }}"
    state: directory
    mode: "700"

- name: Create authorized_keys in /home/centos/.ssh
  file:
    path: "{{ home_directory.path + 'authorized_keys' }}"
    state: touch
    mode: "600"

- name: Copy Pubkey to authorized_keys
  copy:
    dest: "/tmp/localhost/home/centos/.ssh/authorized_keys"
    content: "SSH KEY ABC"

- name: Clone the https://github.com/usegalaxy-eu/mounts repository
  git:
    repo: "https://github.com/usegalaxy-eu/mounts"
    dest: "{{ playbook_dir }}/mounts"
    clone: yes
    update: yes

- name: Include vars of mountpoints.yml into the 'mounts' variable
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/mounts/mountpoints.yml"
    name: mounts

- name: Deploy configuration templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ [root_directory.path, item.dest] | path_join }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ config_templates }}"

- name: Tar the folder structure
  community.general.archive:
    path: "{{ root_directory.path }}"
    dest: "{{ [root_directory.path, 'archive.tgz'] | path_join }}"
    format: gz
    mode: "644"
