---
- name: Create directories for configuration files
  file:
    path: "{{ [root_directory.path, item.dest] | path_join | dirname }}"
    state: directory
    mode: "755"
  loop: "{{ config_templates }}"

- name: Create /home/centos/.ssh directory
  file:
    path: "{{ root_directory.path }}{{ home_directory.path }}.ssh"
    state: directory
    mode: "700"
    owner: 1000
    group: 1000
  when: ssh_authorized_key

- name: Create and copy Pubkey to authorized_keys
  copy:
    dest: "{{ root_directory.path }}{{ home_directory.path }}.ssh/authorized_keys"
    content: "{{ public_key }}"
    mode: "600"
    owner: 1000
    group: 1000
  when: ssh_authorized_key

- name: Clone the https://github.com/usegalaxy-eu/mounts repository
  git:
    repo: "https://github.com/usegalaxy-eu/mounts"
    dest: "{{ playbook_dir }}/mounts"
    clone: yes
    update: yes

- name: Include vars of mountpoints.yml into the 'mounts' variable
  ansible.builtin.include_vars:
    file: "{{ playbook_dir }}/mounts/mountpoints.yml"
    name: mounts

- name: Deploy configuration templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ [root_directory.path, item.dest] | path_join }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ config_templates }}"

- name: Tar the folder structure
  community.general.archive:
    path: "{{ root_directory.path }}"
    dest: "{{ [root_directory.path, 'config.tgz'] | path_join }}"
    format: gz
    mode: "644"
